---
# Service Account for Pattern Detector Monitor
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pattern-detector
  namespace: kube-system
---
# ClusterRole for Monitor Permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pattern-detector
rules:
  # Pod monitoring
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

  # Node monitoring
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]

  # Deployment operations (for scheduler switching)
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "patch", "update"]

  # ReplicaSet monitoring
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch"]

  # StatefulSet monitoring
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list", "watch", "patch", "update"]

  # DaemonSet monitoring
  - apiGroups: ["apps"]
    resources: ["daemonsets"]
    verbs: ["get", "list", "watch"]

  # Events for logging
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch", "update"]

  # Namespaces
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
---
# ClusterRoleBinding for Monitor
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pattern-detector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pattern-detector
subjects:
  - kind: ServiceAccount
    name: pattern-detector
    namespace: kube-system
